### ISSUE TITLE
Constant reloading

### ISSUE THREAD

**Issue by daneoshiga** [FoldingAtHome/fah-web-client#6] opened 2017-10-14 20:28 UTC
Sometimes the client enters in a reload loop that doesn't end, couldn't find any specific cause of pattern, noticing though that opening it in a private window sometimes works.. but sometimes it "just works".

Debugging the code, looks like the root cause has relation with the endpoint `/api/configured` always returning "reload" during the initial setup in the `reset();` clause.

Sorry but couldn't investigate any further than that, hope this report helps finding anything.

The problem happened in Opera 48 and Chrome 61 versions in Ubuntu 16.04

**Comment by MichaIng** [comment] 2018-08-03 15:45
I just recognized the same. At first web UI access went fine. Now after leaving the server for a while an reopen web UI, is constantly reloads the page.

I am willing to help with debugging from here, but need to know where to start.

FAHClient runs on a headless Debian VM (I am currently testing FAH). The service does not show any error message (journalctl).
Browse console shows:
```
Navigated to http://192.168.178.29:7396/
DEBUG: error: VM73 main.js:214
```
where `192.168.178.29` is the server IP.
`/var/lib/fahclient/logs` does not contain logs of the current session. Just the last one, until I toggled `while working`/`idle` within web UI, which restarted the fahclient.

**Comment by sombraguerrero** [comment] 2019-03-06 03:29
I know this issue is posted all over the forum, and it is still very alive and well in 7.5.1.
I think the earlier comments on this ticket were on the right track.
The issue still seems to have something to do with the  reset logic. It continues to be fine when caches are cleared, however, there seems to be one particular offending resource.

`apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&size=standard&origin=http%3A%2F%2F127.0.0.1%3A7396&url=https%3A%2F%2Ffoldingathome.org%2F&gsrc=3p&ic=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en.NiyWKb0spSU.O%2Fam%3DwQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAGLTcCMXphmaCtjiU8wyjr_fEsh11HPRog%2Fm%3D__features__#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Conload&id=I0_1551841690193&_gfid=I0_1551841690193&parent=http%3A%2F%2F127.0.0.1%3A7396&pfname=&rpctoken=31723706:1 Failed to load resource: the server responded with a status of 404 ()`

**Comment by sombraguerrero** [comment] 2019-03-09 18:13
I'll post this on the forums too, because I haven't seen this come up in any prior discussions, but after some more thorough testing and reading, I've come to the conclusion that I think the best way to get around this issue in Chromium-based browsers is to enable the experimental flag for the new caching implementation:
chrome://flags/#enable-simple-cache-backend

**Comment by gbowman** [comment] 2019-03-13 16:24
Thanks Robert.

Greg

—
Gregory R. Bowman
Assistant Professor
Department of Biochemistry & Molecular Biophysics
Washington University School of Medicine
St Louis, Missouri
bowman@biochem.wustl.edu<mailto:bowman@biochem.wustl.edu>



On Mar 9, 2019, at 12:13 PM, Robert Setter <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll post this on the forums too, because I haven't seen this come up in any prior discussions, but after some more thorough testing and reading, I've come to the conclusion that I think the best way to get around this issue in Chromium-based browsers is to enable the experimental flag for the new caching implementation:
chrome://flags/#enable-simple-cache-backend

**Comment by KSib** [comment] 2020-03-05 00:50
Was there ever a proper workaround for this?

**Comment by MichaIng** [comment] 2020-03-05 09:37
Hit ctrl+F5, no solution but an easy short-term fix whenever you face the issue.

**Comment by KSib** [comment] 2020-03-05 14:27
Unfortunately, that's one of the first things I tried and it didn't work. What did work was loading the page in private/incognito mode in Edge.

**Comment by MichaIng** [comment] 2020-03-05 16:55
@KSib 
Interesting, probably Edge does not support this shortcut? When using private/incognito mode fixes the issue, it is nearly a prove that caching is the issue.

**Comment by jpalpant** [comment] 2020-03-06 21:20
I think the issue is with session-id caching. I noticed that when I visit the FAH web control, the resource `js/main.js` is cached by default by Chrome using the in-memory cache:

<img width="716" alt="Screen Shot 2020-03-06 at 1 07 48 PM" src="https://user-images.githubusercontent.com/9629191/76122677-7c704400-5fab-11ea-8bfd-74b615cde4c3.png">

That should be fine, but I noticed that the top of the "Response" (actually just the file loaded from the cache) has a constant `sid` at the top:

<img width="338" alt="Screen Shot 2020-03-06 at 1 08 18 PM" src="https://user-images.githubusercontent.com/9629191/76122713-901baa80-5fab-11ea-96d0-61e3eeece391.png">

Once that session ID loads, the web frontend tries to make API requests using it - but these fail, because the session is considered "expired" by the FAH client. Unfortunately failing an API request due to a bad session id seems to happen with a HTTP 50x, which the client doesn't and shouldn't handle.

This explains why clearing the cache, or toggling the "Disable cache" checkbox in Chrome DevTools, resolves the issue - FAH gets a new session ID.

Here's one _somewhat_ helpful workaround - when running the FAHClient, provide args to prevent session expiry: `--session-lifetime=0 --session-timeout=0`. This only works until the FAHClient restarts, but as long as it runs continuously, your session ID that is cached will stay valid. Once FAHClient restarts I think you'll still have to clear your cache.

By default the session timeout is 3600, which I believe should be in seconds, meaning if you visit the FAH web control client one hour after the session is created, you'll be stuck on the infinity refresh loop.

Better handling of expired sessions on FAHClient would be helpful, but I'm wondering if strictly just not caching `js/main.js` would be sufficient?

**Comment by JBethay** [comment] 2020-03-07 01:09
CTRL+F5 did not work for me, CTRL+SHIFT+R also did not work.
A temporary fix I found that works is is to hit F12 and open the developer tools (tested in both chrome and the new edge) then right click on the refresh button and hit "Empty cache and hard refresh" which got it loading (providing more evidence that this is indeed a client side caching problem.) 

![image](https://user-images.githubusercontent.com/26255513/76133445-2f5d9380-5fe6-11ea-8ff2-a010b528662c.png)

**Comment by BennehR** [comment] 2020-03-07 15:07
> CTRL+F5 did not work for me, CTRL+SHIFT+R also did not work.
> A temporary fix I found that works is is to hit F12 and open the developer tools (tested in both chrome and the new edge) then right click on the refresh button and hit "Empty cache and hard refresh" which got it loading (providing more evidence that this is indeed a client side caching problem.)
> 
> ![image](https://user-images.githubusercontent.com/26255513/76133445-2f5d9380-5fe6-11ea-8ff2-a010b528662c.png)

this worked for me in chrome where the other two shortcuts did not, thank you

**Comment by sombraguerrero** [comment] 2020-03-07 16:59
I very much @jpalpant. I think that's why my experimenting with the Chrome cache flags earlier was having mixed results, because doing so creates new sessions and handles them differently, but ultimately doesn't eliminate the underlying problem. Not caching main.js may very well work, especially because the very best workaround for the problem seems to be running in Incognito/InPrivate sessions. That's really my suggestion to anyone in the interim, @BennehR

**Comment by roycewilliams** [comment] 2020-03-07 18:53
Watching the dev console, the issue appears to be related to Chrome, JavaScript, and HTTP (rather than HTTPS.

But you can also go to https://client.foldingathome.org, which knows how to connect to 127.0.0.1:7396 itself somehow. wrapping it in a different way (also pulling updates with JQuery, I think), so I just set up an SSH tunnel that forwards 7396 on my workstation to 127:0.0.1:7396 on the system, and that seems to have sidestepped the issue for now.

If you're running the client locally, directly using https://client.foldingathome.org might Just Work.

**Comment by chingc** [comment] 2020-03-11 01:24
I'm having the same issue. My current workaround which seems to work every time is to just open it in a private window.

**Comment by roycewilliams** [comment] 2020-03-11 01:46
@chingc This works for a while, but eventually that browser instance is also affected. You have two chances per browser: one in private mode, and one in general mode. I have four Chromium-based browsers installed, and each of them gives me two "chances", but now all eight combinations are exhausted and I'm unable to load the interface anywhere.

**Comment by jcoffland** [comment] 2020-03-11 03:26
It's actually possible to override the Web pages the client uses by placing files under the ``www`` directory where the client runs.  This is also known as the data directory.  Try putting the attached file there and renaming it to ``index.html``.  So on Windows the file should be something like:

    C:\Users\JohnDoe\AppData\Roaming\FAHClient\www\index.html

This replacement ``index.html`` should avoid caching ``main.js``.

[index.txt](https://github.com/FoldingAtHome/fah-web-client/files/4315867/index.txt)

**Comment by cprivite** [comment] 2020-03-11 03:42
@jcoffland Can that be repackaged as a PR for the included index.html file? https://github.com/FoldingAtHome/fah-web-client/blob/master/src/fah/webclient/index.html

**Comment by jpalpant** [comment] 2020-03-11 03:56
@jcoffland had no idea you were a lead on this too! Thanks for chiming in. Is the data directory also the place that stores `cores/`, `work/`, etc? If so, I can't actually get this part working, when I make a new folder `www/` and put that `index.html` there I see FAHClient returning the same old `index.html`. Did I put it under the wrong folder?

**Comment by jcoffland** [comment] 2020-03-11 06:57
Sorry, I see now that this feature is only enabled in the debug version which we have not made public.

I'm afraid there may be no way to fix this until we make a new client release.  A new client is in the works but it is not yet complete and needs more testing.  I am currently working on other parts of F@H.  The good news is that the new client will be Open-Source.  Maybe we can release the source early to get some other developers working with it sooner than later.  I'm not sure how much interest there would be.

**Comment by goncaloperes** [comment] 2020-03-12 08:45
> Hit Ctrl+F5, no solution but an easy short-term fix whenever you face the issue.

On Opera the CTRL+F5 worked for me.
I was having the same problem on Chrome but didn't know the trick by then.

**Comment by MichaIng** [comment] 2020-03-12 13:18
Basically this is the default short cut for a forced reload with cleared cache on Opera. I thought this is generic across all browsers. If course it can be changed via settings.

**Comment by roycewilliams** [comment] 2020-03-12 13:19
This will sometimes initially work for Chrome, but it eventually stops working.

**Comment by MichaIng** [comment] 2020-03-12 13:21
Probably Chrome then has a second cache layer or handles this differently internally.

**Comment by roycewilliams** [comment] 2020-03-12 13:22
Indeed. However, it is still not known how to force the appropriate level of flushing cache. Even using the developer tools to clear all site data fails to address the issue.

**Comment by neslekkim** [comment] 2020-03-14 17:25
> If you're running the client locally, directly using https://client.foldingathome.org might Just Work.

Does not work on Chrome or IE here, installed today, and run 3-4 hours before the page started to reload, after that I haven't been able to open the WebControl anymore.

**Comment by thetayloredman** [comment] 2020-03-14 19:15
F12 and right click reload to press Hard Reload and Clear Cache worked for me.

**Comment by heavybloodloss** [comment] 2020-03-16 01:33
Running on Chrome Version 80.0.3987.132 (Official Build) (64-bit), deleting the cache for 24 hours worked for me.

**Comment by neslekkim** [comment] 2020-03-16 08:18
yes, it works with hard releoad, so that is how it is supposed to work then I guess. ;)

**Comment by lucidyan** [comment] 2020-03-16 12:19
That my recipe for Chrome:

* Open Developers tools <kbd>F12</kbd> or <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>I</kbd> or <kbd>⌘</kbd><kbd>Opt</kbd><kbd>I</kbd>
 * Application
 * Application -> Clear Storage
 * Clear site data

![image](https://user-images.githubusercontent.com/5789108/76757802-60ce2000-6799-11ea-9993-1e9e85f11998.png)

**Comment by pechar** [comment] 2020-03-17 07:33
I believe the issue is pretty clear. The client is requesting some Google FastButton api from 

[https://apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&size=standard&origin=http%3A%2F%2F127.0.0.1%3A7396&url=https%3A%2F%2Ffoldingathome.org%2F&gsrc=3p&ic=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en.OfYsKuVZ3qI.O%2Fam%3DwQE%2Fd%3D1%2Fct%3Dzgms%2Frs%3DAGLTcCMVod3aO7ybjljp3cyn2IsEoP0pUg%2Fm%3D__features__#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Conload&id=I0_1584429722581&_gfid=I0_1584429722581&parent=http%3A%2F%2F127.0.0.1%3A7396&pfname=&rpctoken=35049134](https://apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&size=standard&origin=http%3A%2F%2F127.0.0.1%3A7396&url=https%3A%2F%2Ffoldingathome.org%2F&gsrc=3p&ic=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en.OfYsKuVZ3qI.O%2Fam%3DwQE%2Fd%3D1%2Fct%3Dzgms%2Frs%3DAGLTcCMVod3aO7ybjljp3cyn2IsEoP0pUg%2Fm%3D__features__#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Conload&id=I0_1584429722581&_gfid=I0_1584429722581&parent=http%3A%2F%2F127.0.0.1%3A7396&pfname=&rpctoken=35049134 )

<img width="1654" alt="Screen Shot 2020-03-17 at 08 30 26" src="https://user-images.githubusercontent.com/592348/76832611-f0bbaa80-6829-11ea-8df8-419ab17923fa.png">

And it's returning a 404. Perhaps the resource is down?
<img width="701" alt="Screen Shot 2020-03-17 at 08 29 07" src="https://user-images.githubusercontent.com/592348/76832378-7e4aca80-6829-11ea-80cc-58217aac4714.png">

**Comment by roycewilliams** [comment] 2020-03-17 07:41
It works fine for everyone at first. That resource starts returning a 404 only after a certain amount of time or interaction. Notice the token in the URL.

**Comment by lolmaus** [comment] 2020-03-17 09:02
I have recovered from this issue by simply opening Chrome Dev Tools with network caching disabled.

This indicates that the issue may be with a cached response.

**Comment by Fr4gg1e** [comment] 2020-03-17 21:55
F12, right-click reload button and then selecting "Empty Cache and Hard Reload" fixed it for me.

**Comment by darylknight** [comment] 2020-03-22 15:21
Just signed up to start folding today and ran into this issue in less than 10 minutes. Dev tools, right clicking the refresh icon, emptying cache and hard-refreshing fixed it; it's definitely cache related.

**Comment by DmitryIvanov92** [comment] 2020-03-23 08:09
@beshur has already created a PR to fix it #16

**Comment by Cerrebos** [comment] 2020-03-23 10:41
Opening https://client.foldingathome.org/ on a private chrome tab worked for me today with chrome version  80.0.3987.149

**Comment by jzadra** [comment] 2020-03-23 15:26
> CTRL+F5 did not work for me, CTRL+SHIFT+R also did not work.
> A temporary fix I found that works is is to hit F12 and open the developer tools (tested in both chrome and the new edge) then right click on the refresh button and hit "Empty cache and hard refresh" which got it loading (providing more evidence that this is indeed a client side caching problem.)
> 
> ![image](https://user-images.githubusercontent.com/26255513/76133445-2f5d9380-5fe6-11ea-8ff2-a010b528662c.png)

This worked for me.

**Comment by roycewilliams** [comment] 2020-03-23 15:30
Everyone, please wait a couple of days before posting "me, too" comments, or maybe just hit "like" on the technique that worked for you instead of creating a separate reply.

All of the mitigations people are saying "worked for me" do work ... for a while. And then for many people, they stop working.

**Comment by Bobathernebay** [comment] 2020-03-23 21:14
Use another browser ???

**Comment by cprivite** [comment] 2020-03-23 21:32
It's not a problem with a browser, and it can't be fixed with any matter of keystroke. It's an issue with the javascript design of this page and needs a patch from the maintainers of folding at home.

**Comment by fangio86** [comment] 2020-03-24 16:12
I have the same problem as everyone else. I'm a new user with Chrome.

**Comment by Basil11Sky** [comment] 2020-03-24 17:59
> It's not a problem with a browser, and it can't be fixed with any matter of keystroke. It's an issue with the javascript design of this page and needs a patch from the maintainers of folding at home.
> 
> There is a patch in the works that will hopefully fix it. #16

I have the same problem in Chrome and Vivaldi. F12 etc cures it

**Comment by mbates14** [comment] 2020-03-25 11:47
Me too

**Comment by Nexxxy** [comment] 2020-03-26 10:36
Me too but F12 dont cure it here

**Comment by lolmaus** [comment] 2020-03-26 11:31
@Nexxxy Enable the `Disable cache` checkbox on the Network tab, then refresh the page once.

**Comment by erkexzcx** [comment] 2020-03-26 15:32
I have 2080Ti and Ryzen 3900, yet I can't use my PC for FAH, because of this bug. Absolutely the same issue on both Linux and Windows.

Once this issue is fixed, I will consider trying out FAH once again.

**Comment by Nexxxy** [comment] 2020-03-27 13:38
<3 @lolmaus this works ur awesome

**Comment by pyrite357** [comment] 2020-03-29 21:03
It worked for me in Chrome to open the client in an incognito window, fyi

**Comment by FlorinAndrei** [comment] 2020-03-30 18:33
In my case, it *seemed* (emphasis) to start after I changed my user to lowercase, but the browser had accessed the client before with the mixed case user in config.xml.

I opened dev tools in Chrome and poked around. I don't think I actually did anything, but the issue seemed to have cleared on its own (knock on wood).

**Comment by aszorenyi** [comment] 2020-03-31 12:26
I've disabled the cache a week ago, there is no storage data (dev tool wrote 0 bytes) but the issue is still present. Sometimes it works, but most of the time it just reloads the page constantly.

**Comment by WebMaximus** [comment] 2020-04-04 07:40
Amazing how this issue seems to have been going on for many years! Doing a quick search, I found posts from many years back discussing the very same  thing. I hope it one day can be addressed.

Anyway, what I found always works for me in Chrome (currently on 80.0.3987.149 ) is pressing F12 followed by right-clicking the refresh button and pick the 'Empty cache and hard reload' option.

**Comment by lolmaus** [comment] 2020-04-04 08:11
Should this issue be locked for further discussion?

**Comment by neslekkim** [comment] 2020-04-04 08:16
> Should this issue be locked for further discussion?

Did you fix it?

**Comment by neslekkim** [comment] 2020-04-04 08:20
The webpage or the thing that is serving the webpage need to implement this:
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching

**Comment by lolmaus** [comment] 2020-04-04 09:28
> Did you fix it?

No, why?I'm not suggesting that this issue should be closed.

With the easiest workarounds possible being already posted and upvoted, comments like "It worked for me", "I have the same problem as everyone else", etc — are not helping, but are a source of noise for F@H engineers and scientists working on the codebase.

***

> The webpage or the thing that is serving the webpage need to implement this:
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching

This is exactly what "the thing that is serving the webpage" (the thing? really?) should stop doing.

**Comment by neslekkim** [comment] 2020-04-04 11:17
hehe, the thing, I tried to look through the source, but I couldn't figure out how it's served, on windows, the local app is acting as an webserverhosting one webpage, but how, and where is the source for that?, I only see the webcode in this project. 

Anyway, yes, I read close, not lock..

**Comment by Nekromancer** [comment] 2020-04-04 12:58
Yea, i would love to fix that, but i can't figure out how this is served, what are the contracts etc. Does server side of F@H is open source too? I can't find it

**Comment by cprivite** [comment] 2020-04-04 13:14
Guys if you looked at the history you'd see the patch is already ready to go over here: #16  
So locking the discussion may actually be appropriate. It's now just a matter of rolling it out and verifying it works. I don't know when that'll happen, but that discussion belongs in #16  now.

**Comment by jaybird1944** [comment] 2020-04-05 17:03
> It's not a problem with a browser, and it can't be fixed with any matter of keystroke. It's an issue with the javascript design of this page and needs a patch from the maintainers of folding at home.

I'm using Chrome and,  of course, this is a problem for me.
My wife uses Firefox and does NOT have any problem at all with reloading, so it IS browser related.

**Comment by WebMaximus** [comment] 2020-04-05 17:19
I'm not a web coder but this indeed seems to be an issue with Chrome in particular. 

And considering the market share Chrome has, it would be nice if it could be addressed.

It also makes more sense to me a website is changed to work with one of the largest web browsers in the world rather than the browser is adjusted to work with a single website.

**Comment by fke8859** [comment] 2020-04-15 08:19
Clearing the cache in Chrome has worked for me

**Comment by WebMaximus** [comment] 2020-04-15 09:30
Yeah, this indeed seems to be a cache issue. Which I guess would be a clue figuring out how to address the problem.

**Comment by AnthonyLenglet** [comment] 2020-04-16 11:53
To new people coming to this thread, the solution to the issue is known, but no new release can be put out yet

See https://github.com/FoldingAtHome/fah-web-client/issues/6#issuecomment-597474010

> Sorry, I see now that this feature is only enabled in the debug version which we have not made public.
> 
> I'm afraid there may be no way to fix this until we make a new client release. A new client is in the works but it is not yet complete and needs more testing. I am currently working on other parts of F@H. The good news is that the new client will be Open-Source. Maybe we can release the source early to get some other developers working with it sooner than later. I'm not sure how much interest there would be.

**Comment by blu28** [comment] 2020-04-16 12:50
Running the beta version (7.6.7) fixed the problem for me.  Your mileage may vary.

**Comment by garyzim** [comment] 2020-04-17 08:30
Windows 10
Chrome 81.0.4044.113
Clearing the Chrome cache fixed it for me for now:
Settings>Clear browsing data>Cached images and files

**Comment by jpalpant** [comment] 2020-04-17 23:54
Agree with @blu28; not sure about versions but in v7.6.8+ (public releases list [here](https://download.foldingathome.org/releases/public/release/fahclient/), this is definitely resolved because the client uses a new method of fetching the session ID which will not be cached. Maybe earlier, I don't know if that change went into some earlier release or a beta version.

Thanks @jcoffland :)

**Comment by PantherX** [comment] 2020-04-18 02:44
Please note that the latest stable release 7.6.9 should have addressed this issue. Thus, I will close this issue now.

If you have any other issues, please post in the Official Forum: https://foldingforum.org/index.php for troubleshooting :)

**Closed by PantherX** 2020-04-18 02:44 UTC

**Comment by 3rdRockGuy** [comment] 2020-06-20 17:02
**  "...F12 ... right click on the refresh button ....hit "Empty cache and hard refresh..."  **
**WORKED FOR ME** = **thanks to BennehR** above:
https://github.com/FoldingAtHome/fah-web-client/issues/6#issuecomment-596097749  )
